spring:
  datasource:
    url: jdbc:postgresql://camunda-engine-db.cbbghabknrkl.ap-south-1.rds.amazonaws.com:5432/camunda_db
    username: postgres
    password: postgres

camunda:
  bpm:
    admin-user:
      id: dailype
      password: 12345
    database:
      type: postgres
      schema-update: true
      db-schema-update: true
    job-execution:
      enabled: true
    process-engine:
      name: default
      history-level: full
      async-execution:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
