name:  Ci/ Cd springboot-demo

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'X64','dailype' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: stop old container
      run: sudo docker container stop camunda-engine || true

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Delete old container 
      run: sudo docker container rm camunda-engine || true
    - name: Delete old image 
      run:  sudo docker image rm camunda || true

    - name: Build the Docker image
      run: sudo docker build -t camunda .
      
   
    - name: Run docker image
      run: sudo docker run -d -p 8080:8080 --name camunda-engine camunda sleep infinity| echo "success"
